RoleBasedAppAccess/RoleBasedAppAccess/RoleBasedAppAccess/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RoleBasedAppAccess.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace RoleBasedAppAccess.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }

        /// <summary>
        /// Get All Roles
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        /// <summary>
        /// Create  a New role
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        /// <summary>
        /// Create a New Role
        /// </summary>
        /// <param name="Role"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
     
    }
}

RoleBasedAppAccess/RoleBasedAppAccess/RoleBasedAppAccess/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Add New Role";
}
<h2>Add New Role:</h2>
<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>
@using (Html.BeginForm())
{
    <table style="width:50%; border:solid 4px red; background-color:skyblue; padding:10px;">
        <tr>
            <td style="background:green; color:white; padding:10px;">Role Name:</td>
            <td style="background:green; color:white; padding:10px;">
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>
        <tr><td style="height:20px;" colspan="2"></td></tr>
        <tr><td></td><td><input type="submit" value="Create Role" /></td></tr>
        <tr><td style="height:20px;" colspan="2"></td></tr>
    </table>
}

RoleBasedAppAccess/RoleBasedAppAccess/RoleBasedAppAccess/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Manage Role";
}
<h2>Manage Role</h2>
<table><tr><td style="height:20px;"></td></tr></table>
<table id="tbrole" style="width:30%; border:solid 4px red; background-color:skyblue; padding-left:10px;">
    <tr>
        <td style="background:green; color:white; padding:10px;">
            Role Name
        </td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="padding:10px; border-bottom:1px solid #ff006e;">
                @item.Name
            </td>
        </tr>
    }
</table>
<table>
    <tr><td style="height:20px;"></td></tr>
    <tr>
        <td style="height:20px; text-align:right;">
            @Html.ActionLink("Add New Role", "Create", "Role")
        </td>
    </tr>
</table>